apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: order-service
  namespace: amq-streams-kafka
spec:
  replicas: 1
  selector:
    app: order-service
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: quay.io/vaibhava_srivastava/kafka:order-service
          ports:
            - containerPort: 8080
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - order-service
        from:
          kind: ImageStreamTag
          name: order-service:latest

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: amq-streams-kafka
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: order-service
  namespace: amq-streams-kafka
spec:
  to:
    kind: Service
    name: order-service
  port:
    targetPort: 8080
  tls:
    termination: edge
