apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-email-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-email-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-email-service
    spec:
      containers:
        - name: email-service
          image: "{{ .Values.image.repository }}/email-service:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ index .Values.microservices "email-service" "port" }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-order-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-order-service
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.image.repository }}/order-service:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ index .Values.microservices "order-service" "port" }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-stock-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-stock-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-stock-service
    spec:
      containers:
        - name: stock-service
          image: "{{ .Values.image.repository }}/stock-service:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ index .Values.microservices "stock-service" "port" }}
